apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibops.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibops.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.core.secret.secretKey | quote }}
  JWT_SECRET_KEY: {{ .Values.core.secret.jwtSecretKey | quote }}
  AUTH_USERNAME: {{ .Values.core.secret.authUsername | quote }}
  AUTH_PASSWORD_HASH: {{ .Values.core.secret.authPasswordHash | quote }}
  DATABASE_URL: {{ include "vibops.databaseUrl" . | quote }}
  VIBOPS_LICENCE_KEY: {{ .Values.core.secret.licenceKey | default "" | quote }}
